# Generated by Django 4.0.9 on 2024-01-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt_names', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=200)),
                ('vetstreet_url', models.CharField(blank=True, max_length=200)),
                ('wikipedia_url', models.CharField(blank=True, max_length=200)),
                ('weight_imperial_min', models.PositiveSmallIntegerField()),
                ('weight_imperial_max', models.PositiveSmallIntegerField()),
                ('weight_metric_min', models.PositiveSmallIntegerField()),
                ('weight_metric_max', models.PositiveSmallIntegerField()),
                ('life_span_min', models.PositiveSmallIntegerField()),
                ('life_span_max', models.PositiveSmallIntegerField()),
                ('temperament', models.CharField(blank=True, max_length=200)),
                ('adaptability', models.PositiveSmallIntegerField()),
                ('affection_level', models.PositiveSmallIntegerField()),
                ('child_friendly', models.PositiveSmallIntegerField()),
                ('dog_friendly', models.PositiveSmallIntegerField()),
                ('energy_level', models.PositiveSmallIntegerField()),
                ('grooming', models.PositiveSmallIntegerField()),
                ('health_issues', models.PositiveSmallIntegerField()),
                ('intelligence', models.PositiveSmallIntegerField()),
                ('shedding_level', models.PositiveSmallIntegerField()),
                ('social_needs', models.PositiveSmallIntegerField()),
                ('stranger_friendly', models.PositiveSmallIntegerField()),
                ('vocalisation', models.PositiveSmallIntegerField()),
                ('indoor', models.BooleanField(blank=True, null=True)),
                ('experimental', models.BooleanField(blank=True, null=True)),
                ('hairless', models.BooleanField(blank=True, null=True)),
                ('natural', models.BooleanField(blank=True, null=True)),
                ('rare', models.BooleanField(blank=True, null=True)),
                ('rex', models.BooleanField(blank=True, null=True)),
                ('suppressed_tail', models.BooleanField(blank=True, null=True)),
                ('short_legs', models.BooleanField(blank=True, null=True)),
                ('hypoallergenic', models.BooleanField(blank=True, null=True)),
                ('reference_image_id', models.CharField(blank=True, max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeds', to='breeds.image')),
            ],
        ),
    ]
