# Generated by Django 4.0.9 on 2024-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_alter_breed_adaptability_alter_breed_affection_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='image'),
        ),
    ]
